#!/usr/bin/env python3
"""Deterministically extract group-discussion transcript PDFs into plain text.

Writes, under the work directory:
  <work>/text/D1.txt ...   one normalized text file per input PDF
  <work>/manifest.json     doc IDs, source paths, page counts, char counts, hashes
  <work>/section0.md       the "## 0. 入力一覧" table, verbatim for the report

No summarization happens here — this half must stay deterministic so the
report's input inventory can never be hand-written.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
import unicodedata
from datetime import datetime
from pathlib import Path

PAGE_BREAK = "\f"


def die(msg: str) -> None:
    print(f"Error: {msg}", file=sys.stderr)
    sys.exit(1)


def normalize(text: str) -> str:
    """NFKC + whitespace cleanup, page breaks preserved as \\f."""
    text = unicodedata.normalize("NFKC", text)
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    # collapse runs of spaces/tabs but keep line and page structure
    text = re.sub(r"[ \t　]+", " ", text)
    text = re.sub(r" *\n *", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip() + "\n"


def extract_one(pdf: Path) -> str:
    if shutil.which("pdftotext") is None:
        die("pdftotext is required (poppler-utils). Install it and re-run.")
    proc = subprocess.run(
        ["pdftotext", "-layout", "-enc", "UTF-8", str(pdf), "-"],
        capture_output=True,
    )
    if proc.returncode != 0:
        die(f"pdftotext failed on {pdf}: {proc.stderr.decode('utf-8', 'replace').strip()}")
    return proc.stdout.decode("utf-8", "replace")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "pdfs", nargs="+", help="transcript PDFs — the order given on the command line fixes the D<n> IDs"
    )
    ap.add_argument("--work", required=True, help="work directory for extracted text")
    args = ap.parse_args()

    resolved = [str(Path(p).resolve()) for p in args.pdfs]
    dupes = {p for p in resolved if resolved.count(p) > 1}
    if dupes:
        die(f"the same PDF was passed twice: {sorted(dupes)}")

    work = Path(args.work)
    text_dir = work / "text"
    # one-shot: drop text from a previous run so a shrunk input set leaves no
    # stale D<n>.txt that a reader could glob in alongside the current manifest
    if text_dir.exists():
        for stale in text_dir.glob("D*.txt"):
            stale.unlink()
    text_dir.mkdir(parents=True, exist_ok=True)

    docs = []
    for i, raw in enumerate(args.pdfs, start=1):
        pdf = Path(raw)
        if not pdf.is_file():
            die(f"input not found: {pdf}")
        if pdf.suffix.lower() != ".pdf":
            die(f"not a PDF: {pdf}")
        text = normalize(extract_one(pdf))
        pages = text.count(PAGE_BREAK) + 1
        body = text.replace(PAGE_BREAK, "\n")
        chars = len(re.sub(r"\s", "", body))
        if chars < 200:
            print(
                f"Warning: {pdf.name} yielded only {chars} non-space chars — "
                "likely a scanned/image PDF with no text layer",
                file=sys.stderr,
            )
        doc_id = f"D{i}"
        (work / "text" / f"{doc_id}.txt").write_text(text, encoding="utf-8")
        docs.append(
            {
                "id": doc_id,
                "source": str(pdf.resolve()),
                "name": pdf.name,
                "pages": pages,
                "chars": chars,
                "sha256": hashlib.sha256(pdf.read_bytes()).hexdigest()[:16],
            }
        )

    manifest = {
        "generated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "docs": docs,
    }
    (work / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )

    lines = [
        "## 0. 入力一覧",
        "",
        "<!-- generated by extract_transcripts.py — do not hand-edit -->",
        "",
        "| ID | ファイル | ページ数 | 文字数(空白除く) | sha256(先頭16) |",
        "| -- | -------- | -------- | ---------------- | -------------- |",
    ]
    for d in docs:
        lines.append(
            f"| {d['id']} | {d['name']} | {d['pages']} | {d['chars']} | `{d['sha256']}` |"
        )
    # NOTE: no timestamp here — section0.md is embedded verbatim in the report
    # and compared byte-for-byte, so it must be a pure function of the inputs.
    # The extraction time lives in manifest.json only.
    lines += [""]
    (work / "section0.md").write_text("\n".join(lines), encoding="utf-8")

    print(f"extracted {len(docs)} PDF(s) -> {work}")
    for d in docs:
        print(f"  {d['id']}: {d['name']} ({d['pages']}p, {d['chars']} chars)")


if __name__ == "__main__":
    main()
